// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvgzvvzlwigoqfvmilsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Z3p2dnpsd2lnb3Fmdm1pbHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTQ3MTEsImV4cCI6MjA3MTczMDcxMX0.le769UTA-HWmjR7MWRIoV4nvTPAdRvHowaP9TrBgp4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});